import { Noto_Sans } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Noto = Noto_Sans({
    subsets: ['latin'],
    variable: '--font-notosans',
    weights: [400, 400, 500, 600, 700],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${Noto.variable} font-sans`}>
      <body>{children}</body>
    </html>
  );
}
